-- Add is_grok column to post_comments for AI-generated comments
ALTER TABLE public.post_comments 
ADD COLUMN is_grok boolean NOT NULL DEFAULT false;

-- Create index for quick filtering
CREATE INDEX idx_post_comments_is_grok ON public.post_comments(is_grok) WHERE is_grok = true;

-- Add comment
COMMENT ON COLUMN public.post_comments.is_grok IS 'True if this comment was generated by Grok AI';