// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://hvtpfbfawhmkvjtcyaxs.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2dHBmYmZhd2hta3ZqdGN5YXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY4OTU4MjYsImV4cCI6MjA4MjQ3MTgyNn0.sYmL5RFcgfVH3EExftCjEWRv6ctZh5QxB6KWcGxVYrA';

// Supabase client for all operations
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

export { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY };
